stages:
  train:
    cmd: >-
      python -m ml.cloud_train
      --mlflow-uri ${DATABRICKS_HOST}
    deps:
      - ml/
      - requirements.txt
    params:
      - train.epochs
      - train.batch_size
      - train.learning_rate
    outs:
      - models/model.pkl
      - training_history.csv
      - confusion_matrix.png
    metrics:
      - metrics.json:
          cache: false
    plots:
      - training_history.csv:
          x: stage
          y: train_loss
      - training_history.csv:
          x: stage
          y: test_loss
      - training_history.csv:
          x: stage
          y: train_accuracy
      - training_history.csv:
          x: stage
          y: test_accuracy
      - training_history.csv:
          x: stage
          y: train_f1
      - training_history.csv:
          x: stage
          y: test_f1
      - confusion_matrix.png

  evaluate:
    cmd: python -m ml.evaluate
    deps:
      - models/model.pkl
      - data/test/
    outs:
      - evaluation_results.json
    metrics:
      - evaluation_results.json:
          cache: false