train:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam
  validation_split: 0.2

model:
  architecture: sequential
  hidden_layers: [128, 64, 32]
  dropout_rate: 0.3
  activation: relu